"""Add contact_messages table

Revision ID: 1bb0b74ab65b
Revises: 738748682e44
Create Date: 2026-08-04 16:31:54.027133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb0b74ab65b'
down_revision = '738748682e44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
