"""remove health and productivity

Revision ID: 1c261e5ccd62
Revises: 81567fb6566c
Create Date: 2026-07-31 16:00:41.472138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c261e5ccd62'
down_revision = '81567fb6566c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_period_cycles_id', table_name='period_cycles')
    op.drop_index('ix_period_cycles_user_id', table_name='period_cycles')
    op.drop_table('period_cycles')
    op.drop_index('ix_note_items_id', table_name='note_items')
    op.drop_index('ix_note_items_user_id', table_name='note_items')
    op.drop_table('note_items')
    op.drop_index('ix_daily_journals_id', table_name='daily_journals')
    op.drop_index('ix_daily_journals_user_id', table_name='daily_journals')
    op.drop_table('daily_journals')
    op.drop_index('ix_todo_items_id', table_name='todo_items')
    op.drop_index('ix_todo_items_user_id', table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index('ix_step_logs_id', table_name='step_logs')
    op.drop_index('ix_step_logs_log_date', table_name='step_logs')
    op.drop_index('ix_step_logs_user_id', table_name='step_logs')
    op.drop_table('step_logs')
    op.drop_index('ix_water_logs_id', table_name='water_logs')
    op.drop_index('ix_water_logs_user_id', table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index('ix_bmi_profiles_id', table_name='bmi_profiles')
    op.drop_index('ix_bmi_profiles_user_id', table_name='bmi_profiles')
    op.drop_table('bmi_profiles')
    op.drop_index('ix_voice_notes_id', table_name='voice_notes')
    op.drop_index('ix_voice_notes_user_id', table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_index('ix_clipboard_items_id', table_name='clipboard_items')
    op.drop_index('ix_clipboard_items_user_id', table_name='clipboard_items')
    op.drop_table('clipboard_items')
    op.drop_index('ix_reminder_alerts_id', table_name='reminder_alerts')
    op.drop_index('ix_reminder_alerts_user_id', table_name='reminder_alerts')
    op.drop_table('reminder_alerts')
    op.drop_index('ix_habit_records_id', table_name='habit_records')
    op.drop_index('ix_habit_records_user_id', table_name='habit_records')
    op.drop_table('habit_records')
    op.drop_index('ix_calendar_events_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_user_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_sleep_logs_id', table_name='sleep_logs')
    op.drop_index('ix_sleep_logs_user_id', table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index('ix_focus_sessions_id', table_name='focus_sessions')
    op.drop_index('ix_focus_sessions_user_id', table_name='focus_sessions')
    op.drop_table('focus_sessions')
    op.drop_index('ix_calorie_logs_id', table_name='calorie_logs')
    op.drop_index('ix_calorie_logs_user_id', table_name='calorie_logs')
    op.drop_table('calorie_logs')
    op.drop_index('ix_goal_trackers_id', table_name='goal_trackers')
    op.drop_index('ix_goal_trackers_user_id', table_name='goal_trackers')
    op.drop_table('goal_trackers')
    op.drop_index('ix_medication_alerts_id', table_name='medication_alerts')
    op.drop_index('ix_medication_alerts_user_id', table_name='medication_alerts')
    op.drop_table('medication_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medication_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_to_take', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medication_alerts_pkey')
    )
    op.create_index('ix_medication_alerts_user_id', 'medication_alerts', ['user_id'], unique=False)
    op.create_index('ix_medication_alerts_id', 'medication_alerts', ['id'], unique=False)
    op.create_table('goal_trackers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='goal_trackers_pkey')
    )
    op.create_index('ix_goal_trackers_user_id', 'goal_trackers', ['user_id'], unique=False)
    op.create_index('ix_goal_trackers_id', 'goal_trackers', ['id'], unique=False)
    op.create_table('calorie_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meal_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calorie_logs_pkey')
    )
    op.create_index('ix_calorie_logs_user_id', 'calorie_logs', ['user_id'], unique=False)
    op.create_index('ix_calorie_logs_id', 'calorie_logs', ['id'], unique=False)
    op.create_table('focus_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='focus_sessions_pkey')
    )
    op.create_index('ix_focus_sessions_user_id', 'focus_sessions', ['user_id'], unique=False)
    op.create_index('ix_focus_sessions_id', 'focus_sessions', ['id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hours_slept', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sleep_logs_pkey')
    )
    op.create_index('ix_sleep_logs_user_id', 'sleep_logs', ['user_id'], unique=False)
    op.create_index('ix_sleep_logs_id', 'sleep_logs', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calendar_events_pkey')
    )
    op.create_index('ix_calendar_events_user_id', 'calendar_events', ['user_id'], unique=False)
    op.create_index('ix_calendar_events_id', 'calendar_events', ['id'], unique=False)
    op.create_table('habit_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('habit_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='habit_records_pkey')
    )
    op.create_index('ix_habit_records_user_id', 'habit_records', ['user_id'], unique=False)
    op.create_index('ix_habit_records_id', 'habit_records', ['id'], unique=False)
    op.create_table('reminder_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trigger_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reminder_alerts_pkey')
    )
    op.create_index('ix_reminder_alerts_user_id', 'reminder_alerts', ['user_id'], unique=False)
    op.create_index('ix_reminder_alerts_id', 'reminder_alerts', ['id'], unique=False)
    op.create_table('clipboard_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('copied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clipboard_items_pkey')
    )
    op.create_index('ix_clipboard_items_user_id', 'clipboard_items', ['user_id'], unique=False)
    op.create_index('ix_clipboard_items_id', 'clipboard_items', ['id'], unique=False)
    op.create_table('voice_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='voice_notes_pkey')
    )
    op.create_index('ix_voice_notes_user_id', 'voice_notes', ['user_id'], unique=False)
    op.create_index('ix_voice_notes_id', 'voice_notes', ['id'], unique=False)
    op.create_table('bmi_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bmi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bmi_profiles_pkey')
    )
    op.create_index('ix_bmi_profiles_user_id', 'bmi_profiles', ['user_id'], unique=False)
    op.create_index('ix_bmi_profiles_id', 'bmi_profiles', ['id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_ml', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='water_logs_pkey')
    )
    op.create_index('ix_water_logs_user_id', 'water_logs', ['user_id'], unique=False)
    op.create_index('ix_water_logs_id', 'water_logs', ['id'], unique=False)
    op.create_table('step_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='step_logs_pkey')
    )
    op.create_index('ix_step_logs_user_id', 'step_logs', ['user_id'], unique=False)
    op.create_index('ix_step_logs_log_date', 'step_logs', ['log_date'], unique=True)
    op.create_index('ix_step_logs_id', 'step_logs', ['id'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todo_items_pkey')
    )
    op.create_index('ix_todo_items_user_id', 'todo_items', ['user_id'], unique=False)
    op.create_index('ix_todo_items_id', 'todo_items', ['id'], unique=False)
    op.create_table('daily_journals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mood', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_journals_pkey')
    )
    op.create_index('ix_daily_journals_user_id', 'daily_journals', ['user_id'], unique=False)
    op.create_index('ix_daily_journals_id', 'daily_journals', ['id'], unique=False)
    op.create_table('note_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='note_items_pkey')
    )
    op.create_index('ix_note_items_user_id', 'note_items', ['user_id'], unique=False)
    op.create_index('ix_note_items_id', 'note_items', ['id'], unique=False)
    op.create_table('period_cycles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('symptoms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='period_cycles_pkey')
    )
    op.create_index('ix_period_cycles_user_id', 'period_cycles', ['user_id'], unique=False)
    op.create_index('ix_period_cycles_id', 'period_cycles', ['id'], unique=False)
    # ### end Alembic commands ###
