"""Add header_image_url to forms

Revision ID: 6dd4c762a44e
Revises: 1c261e5ccd62
Create Date: 2026-08-01 10:28:16.937916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd4c762a44e'
down_revision = '1c261e5ccd62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_responses', sa.Column('respondent_device', sa.String(), nullable=True))
    op.add_column('form_responses', sa.Column('respondent_ip', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('header_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'header_image_url')
    op.drop_column('form_responses', 'respondent_ip')
    op.drop_column('form_responses', 'respondent_device')
    # ### end Alembic commands ###
