"""Add productivity tables

Revision ID: 78a25cb80e44
Revises: f644174e7ef2
Create Date: 2026-07-21 15:28:59.809498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a25cb80e44'
down_revision = 'f644174e7ef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('clipboard_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('copied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipboard_items_id'), 'clipboard_items', ['id'], unique=False)
    op.create_index(op.f('ix_clipboard_items_user_id'), 'clipboard_items', ['user_id'], unique=False)
    op.create_table('daily_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_journals_id'), 'daily_journals', ['id'], unique=False)
    op.create_index(op.f('ix_daily_journals_user_id'), 'daily_journals', ['user_id'], unique=False)
    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_sessions_id'), 'focus_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.create_table('goal_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_trackers_id'), 'goal_trackers', ['id'], unique=False)
    op.create_index(op.f('ix_goal_trackers_user_id'), 'goal_trackers', ['user_id'], unique=False)
    op.create_table('note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_items_id'), 'note_items', ['id'], unique=False)
    op.create_index(op.f('ix_note_items_user_id'), 'note_items', ['user_id'], unique=False)
    op.create_table('reminder_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('trigger_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_alerts_id'), 'reminder_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_alerts_user_id'), 'reminder_alerts', ['user_id'], unique=False)
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_items_id'), 'todo_items', ['id'], unique=False)
    op.create_index(op.f('ix_todo_items_user_id'), 'todo_items', ['user_id'], unique=False)
    op.create_table('voice_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notes_id'), 'voice_notes', ['id'], unique=False)
    op.create_index(op.f('ix_voice_notes_user_id'), 'voice_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_notes_user_id'), table_name='voice_notes')
    op.drop_index(op.f('ix_voice_notes_id'), table_name='voice_notes')
    op.drop_table('voice_notes')
    op.drop_index(op.f('ix_todo_items_user_id'), table_name='todo_items')
    op.drop_index(op.f('ix_todo_items_id'), table_name='todo_items')
    op.drop_table('todo_items')
    op.drop_index(op.f('ix_reminder_alerts_user_id'), table_name='reminder_alerts')
    op.drop_index(op.f('ix_reminder_alerts_id'), table_name='reminder_alerts')
    op.drop_table('reminder_alerts')
    op.drop_index(op.f('ix_note_items_user_id'), table_name='note_items')
    op.drop_index(op.f('ix_note_items_id'), table_name='note_items')
    op.drop_table('note_items')
    op.drop_index(op.f('ix_goal_trackers_user_id'), table_name='goal_trackers')
    op.drop_index(op.f('ix_goal_trackers_id'), table_name='goal_trackers')
    op.drop_table('goal_trackers')
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_id'), table_name='focus_sessions')
    op.drop_table('focus_sessions')
    op.drop_index(op.f('ix_daily_journals_user_id'), table_name='daily_journals')
    op.drop_index(op.f('ix_daily_journals_id'), table_name='daily_journals')
    op.drop_table('daily_journals')
    op.drop_index(op.f('ix_clipboard_items_user_id'), table_name='clipboard_items')
    op.drop_index(op.f('ix_clipboard_items_id'), table_name='clipboard_items')
    op.drop_table('clipboard_items')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
