"""empty message

Revision ID: 7fa5df9d6cc3
Revises: 414fa0ecbd5e
Create Date: 2026-07-27 18:55:13.347876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa5df9d6cc3'
down_revision = '414fa0ecbd5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
