"""add sku to salerecord

Revision ID: 81567fb6566c
Revises: 7fa5df9d6cc3
Create Date: 2026-07-29 11:26:23.871645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81567fb6566c'
down_revision = '7fa5df9d6cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_cards', sa.Column('card_design_type', sa.String(), nullable=True))
    op.add_column('business_cards', sa.Column('custom_message', sa.String(), nullable=True))
    op.add_column('sales_records', sa.Column('sku', sa.String(), nullable=True))
    op.drop_column('stock_movements', 'phone')
    op.drop_column('stock_movements', 'company_name')
    op.drop_column('stock_movements', 'address')
    op.drop_column('stock_movements', 'email')
    op.drop_column('stock_movements', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_movements', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_movements', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_movements', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_movements', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sales_records', 'sku')
    op.drop_column('business_cards', 'custom_message')
    op.drop_column('business_cards', 'card_design_type')
    # ### end Alembic commands ###
