"""add sku to salerecord

Revision ID: 81567fb6566c
Revises: 7fa5df9d6cc3
Create Date: 2026-07-29 11:26:23.871645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81567fb6566c'
down_revision = '7fa5df9d6cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_cards', sa.Column('card_design_type', sa.String(), nullable=True))
    op.add_column('business_cards', sa.Column('custom_message', sa.String(), nullable=True))
    op.add_column('sales_records', sa.Column('sku', sa.String(), nullable=True))
    # removed incorrect drop_column for stock_movements
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # removed incorrect add_column for stock_movements
    op.drop_column('sales_records', 'sku')
    op.drop_column('business_cards', 'custom_message')
    op.drop_column('business_cards', 'card_design_type')
    # ### end Alembic commands ###
