"""Add allow_multiple_responses to forms

Revision ID: 9f537db3181d
Revises: 6dd4c762a44e
Create Date: 2026-08-01 13:45:59.152825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f537db3181d'
down_revision = '6dd4c762a44e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('allow_multiple_responses', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'allow_multiple_responses')
    # ### end Alembic commands ###
