"""Add LoanDesk MVP models

Revision ID: b2bd162a5e6f
Revises: c00a5c47c129
Create Date: 2026-08-18 16:57:48.449768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bd162a5e6f'
down_revision = 'c00a5c47c129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_type', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('office_contact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('banker_loan_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('loan_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banker_loan_preferences_id'), 'banker_loan_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_banker_loan_preferences_user_id'), 'banker_loan_preferences', ['user_id'], unique=False)
    op.create_table('banker_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banker_organizations_id'), 'banker_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_banker_organizations_organization_id'), 'banker_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_banker_organizations_user_id'), 'banker_organizations', ['user_id'], unique=False)
    op.create_table('banker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banker_profiles_id'), 'banker_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_banker_profiles_user_id'), 'banker_profiles', ['user_id'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('udyam_number', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_business_name'), 'customers', ['business_name'], unique=False)
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_gstin'), 'customers', ['gstin'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_index(op.f('ix_customers_pan'), 'customers', ['pan'], unique=False)
    op.create_index(op.f('ix_customers_udyam_number'), 'customers', ['udyam_number'], unique=False)
    op.create_table('loan_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('banker_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('loan_type', sa.String(), nullable=False),
    sa.Column('loan_purpose', sa.String(), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('existing_emi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('existing_liabilities', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['banker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_cases_banker_id'), 'loan_cases', ['banker_id'], unique=False)
    op.create_index(op.f('ix_loan_cases_case_number'), 'loan_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_loan_cases_customer_id'), 'loan_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loan_cases_id'), 'loan_cases', ['id'], unique=False)
    op.create_index(op.f('ix_loan_cases_organization_id'), 'loan_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_loan_cases_status'), 'loan_cases', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('ocr_status', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('document_status', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['loan_cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_loan_cases_status'), table_name='loan_cases')
    op.drop_index(op.f('ix_loan_cases_organization_id'), table_name='loan_cases')
    op.drop_index(op.f('ix_loan_cases_id'), table_name='loan_cases')
    op.drop_index(op.f('ix_loan_cases_customer_id'), table_name='loan_cases')
    op.drop_index(op.f('ix_loan_cases_case_number'), table_name='loan_cases')
    op.drop_index(op.f('ix_loan_cases_banker_id'), table_name='loan_cases')
    op.drop_table('loan_cases')
    op.drop_index(op.f('ix_customers_udyam_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_pan'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_gstin'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_banker_profiles_user_id'), table_name='banker_profiles')
    op.drop_index(op.f('ix_banker_profiles_id'), table_name='banker_profiles')
    op.drop_table('banker_profiles')
    op.drop_index(op.f('ix_banker_organizations_user_id'), table_name='banker_organizations')
    op.drop_index(op.f('ix_banker_organizations_organization_id'), table_name='banker_organizations')
    op.drop_index(op.f('ix_banker_organizations_id'), table_name='banker_organizations')
    op.drop_table('banker_organizations')
    op.drop_index(op.f('ix_banker_loan_preferences_user_id'), table_name='banker_loan_preferences')
    op.drop_index(op.f('ix_banker_loan_preferences_id'), table_name='banker_loan_preferences')
    op.drop_table('banker_loan_preferences')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
