"""Add customer number

Revision ID: b8c25cf4569d
Revises: 3e528d9394a2
Create Date: 2026-08-27 11:51:20.961395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c25cf4569d'
down_revision = '3e528d9394a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_number', sa.String(), nullable=True))
    
    # Backfill customer_number for existing customers
    from sqlalchemy.sql import text
    import string
    import random
    
    def generate_customer_number():
        """Fallback generator in case utils.ids is not available during migration"""
        random_chars = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        return f"CUST-{random_chars}"
    
    conn = op.get_bind()
    res = conn.execute(text("SELECT id FROM customers WHERE customer_number IS NULL"))
    for row in res.fetchall():
        conn.execute(
            text("UPDATE customers SET customer_number = :num WHERE id = :id"),
            {"num": generate_customer_number(), "id": row[0]}
        )
        
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_column('customers', 'customer_number')
    # ### end Alembic commands ###
