"""Add account deletion request table

Revision ID: c00a5c47c129
Revises: 1bb0b74ab65b
Create Date: 2026-08-04 21:16:24.466952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00a5c47c129'
down_revision = '1bb0b74ab65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_deletion_requests_email'), 'account_deletion_requests', ['email'], unique=False)
    op.create_index(op.f('ix_account_deletion_requests_id'), 'account_deletion_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_deletion_requests_id'), table_name='account_deletion_requests')
    op.drop_index(op.f('ix_account_deletion_requests_email'), table_name='account_deletion_requests')
    op.drop_table('account_deletion_requests')
    # ### end Alembic commands ###
