"""Add health tables

Revision ID: f644174e7ef2
Revises: f941ef0ee00b
Create Date: 2026-07-21 15:23:57.625962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f644174e7ef2'
down_revision = 'f941ef0ee00b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmi_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bmi_profiles_id'), 'bmi_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_bmi_profiles_user_id'), 'bmi_profiles', ['user_id'], unique=False)
    op.create_table('calorie_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meal_name', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calorie_logs_id'), 'calorie_logs', ['id'], unique=False)
    op.create_index(op.f('ix_calorie_logs_user_id'), 'calorie_logs', ['user_id'], unique=False)
    op.create_table('habit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('habit_name', sa.String(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_records_id'), 'habit_records', ['id'], unique=False)
    op.create_index(op.f('ix_habit_records_user_id'), 'habit_records', ['user_id'], unique=False)
    op.create_table('medication_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('medication_name', sa.String(), nullable=True),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('time_to_take', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_alerts_id'), 'medication_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_medication_alerts_user_id'), 'medication_alerts', ['user_id'], unique=False)
    op.create_table('period_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_cycles_id'), 'period_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_period_cycles_user_id'), 'period_cycles', ['user_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hours_slept', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_id'), 'sleep_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    op.create_table('step_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_logs_id'), 'step_logs', ['id'], unique=False)
    op.create_index(op.f('ix_step_logs_log_date'), 'step_logs', ['log_date'], unique=True)
    op.create_index(op.f('ix_step_logs_user_id'), 'step_logs', ['user_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount_ml', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_id'), 'water_logs', ['id'], unique=False)
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_id'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_step_logs_user_id'), table_name='step_logs')
    op.drop_index(op.f('ix_step_logs_log_date'), table_name='step_logs')
    op.drop_index(op.f('ix_step_logs_id'), table_name='step_logs')
    op.drop_table('step_logs')
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_id'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_period_cycles_user_id'), table_name='period_cycles')
    op.drop_index(op.f('ix_period_cycles_id'), table_name='period_cycles')
    op.drop_table('period_cycles')
    op.drop_index(op.f('ix_medication_alerts_user_id'), table_name='medication_alerts')
    op.drop_index(op.f('ix_medication_alerts_id'), table_name='medication_alerts')
    op.drop_table('medication_alerts')
    op.drop_index(op.f('ix_habit_records_user_id'), table_name='habit_records')
    op.drop_index(op.f('ix_habit_records_id'), table_name='habit_records')
    op.drop_table('habit_records')
    op.drop_index(op.f('ix_calorie_logs_user_id'), table_name='calorie_logs')
    op.drop_index(op.f('ix_calorie_logs_id'), table_name='calorie_logs')
    op.drop_table('calorie_logs')
    op.drop_index(op.f('ix_bmi_profiles_user_id'), table_name='bmi_profiles')
    op.drop_index(op.f('ix_bmi_profiles_id'), table_name='bmi_profiles')
    op.drop_table('bmi_profiles')
    # ### end Alembic commands ###
