"""Add business tables

Revision ID: f941ef0ee00b
Revises: 
Create Date: 2026-07-21 15:06:09.913424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f941ef0ee00b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_cards_id'), 'business_cards', ['id'], unique=False)
    op.create_index(op.f('ix_business_cards_user_id'), 'business_cards', ['user_id'], unique=True)
    op.create_table('business_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_expenses_id'), 'business_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_business_expenses_user_id'), 'business_expenses', ['user_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=True),
    sa.Column('minimum_stock_level', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_items_user_id'), 'inventory_items', ['user_id'], unique=False)
    op.create_table('invoice_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('is_gst_invoice', sa.Boolean(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_records_id'), 'invoice_records', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_records_invoice_number'), 'invoice_records', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoice_records_user_id'), 'invoice_records', ['user_id'], unique=False)
    op.create_table('quotation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quotation_number', sa.String(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_records_id'), 'quotation_records', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_records_quotation_number'), 'quotation_records', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_quotation_records_user_id'), 'quotation_records', ['user_id'], unique=False)
    op.create_table('receipt_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('received_from', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_records_id'), 'receipt_records', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_records_receipt_number'), 'receipt_records', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_receipt_records_user_id'), 'receipt_records', ['user_id'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_records_id'), 'sales_records', ['id'], unique=False)
    op.create_index(op.f('ix_sales_records_user_id'), 'sales_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_records_user_id'), table_name='sales_records')
    op.drop_index(op.f('ix_sales_records_id'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index(op.f('ix_receipt_records_user_id'), table_name='receipt_records')
    op.drop_index(op.f('ix_receipt_records_receipt_number'), table_name='receipt_records')
    op.drop_index(op.f('ix_receipt_records_id'), table_name='receipt_records')
    op.drop_table('receipt_records')
    op.drop_index(op.f('ix_quotation_records_user_id'), table_name='quotation_records')
    op.drop_index(op.f('ix_quotation_records_quotation_number'), table_name='quotation_records')
    op.drop_index(op.f('ix_quotation_records_id'), table_name='quotation_records')
    op.drop_table('quotation_records')
    op.drop_index(op.f('ix_invoice_records_user_id'), table_name='invoice_records')
    op.drop_index(op.f('ix_invoice_records_invoice_number'), table_name='invoice_records')
    op.drop_index(op.f('ix_invoice_records_id'), table_name='invoice_records')
    op.drop_table('invoice_records')
    op.drop_index(op.f('ix_inventory_items_user_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_business_expenses_user_id'), table_name='business_expenses')
    op.drop_index(op.f('ix_business_expenses_id'), table_name='business_expenses')
    op.drop_table('business_expenses')
    op.drop_index(op.f('ix_business_cards_user_id'), table_name='business_cards')
    op.drop_index(op.f('ix_business_cards_id'), table_name='business_cards')
    op.drop_table('business_cards')
    # ### end Alembic commands ###
